### ISSUE TITLE
Every map failure is duplicated thrice

### ISSUE THREAD

**Issue by ronaldtse** [interscript/maps#5]
https://github.com/interscript/maps/runs/3046655362?check_suite_focus=true

```
2021-07-12T12:46:47.6750074Z Failures:
2021-07-12T12:46:47.6750338Z 
2021-07-12T12:46:47.6751913Z   1) Interscript Interscript::Interpreter iso-ara-Arab-Latn-233-2-1993 system test for الرِيَاض
2021-07-12T12:46:47.6752913Z      Failure/Error: expect(result).to eq(expected)
2021-07-12T12:46:47.6753335Z 
2021-07-12T12:46:47.6753875Z        expected: "al-Riyaḍ"
2021-07-12T12:46:47.6754844Z             got: "al-Riyāḍ"
2021-07-12T12:46:47.6755121Z 
2021-07-12T12:46:47.6755492Z        (compared using ==)
2021-07-12T12:46:47.6756311Z      # ./spec/interscript_spec.rb:32:in `block (8 levels) in <top (required)>'
2021-07-12T12:46:47.6757304Z      # ./spec/interscript_spec.rb:30:in `block (7 levels) in <top (required)>'
2021-07-12T12:46:47.6757758Z 
2021-07-12T12:46:47.6758948Z   2) Interscript Interscript::Interpreter iso-ara-Arab-Latn-233-2-1993 system test for سَأَلَ
2021-07-12T12:46:47.6759926Z      Failure/Error: expect(result).to eq(expected)
2021-07-12T12:46:47.6760334Z 
2021-07-12T12:46:47.6760842Z        expected: "Sa’al"
2021-07-12T12:46:47.6761393Z             got: "Sa’aal"
2021-07-12T12:46:47.6761659Z 
2021-07-12T12:46:47.6762032Z        (compared using ==)
2021-07-12T12:46:47.6762966Z      # ./spec/interscript_spec.rb:32:in `block (8 levels) in <top (required)>'
2021-07-12T12:46:47.6763970Z      # ./spec/interscript_spec.rb:30:in `block (7 levels) in <top (required)>'
2021-07-12T12:46:47.6764436Z 
2021-07-12T12:46:47.6765673Z   3) Interscript Interscript::Interpreter iso-ara-Arab-Latn-233-2-1993 system test for الشَّمْسُ
2021-07-12T12:46:47.6766528Z      Failure/Error: expect(result).to eq(expected)
2021-07-12T12:46:47.6766882Z 
2021-07-12T12:46:47.6767328Z        expected: "al-Šams"
2021-07-12T12:46:47.6767826Z             got: "al-Šaّms"
2021-07-12T12:46:47.6768062Z 
2021-07-12T12:46:47.6768385Z        (compared using ==)
2021-07-12T12:46:47.6769139Z      # ./spec/interscript_spec.rb:32:in `block (8 levels) in <top (required)>'
2021-07-12T12:46:47.6770000Z      # ./spec/interscript_spec.rb:30:in `block (7 levels) in <top (required)>'
2021-07-12T12:46:47.6770405Z 
2021-07-12T12:46:47.6771414Z   4) Interscript Interscript::Compiler::Ruby iso-ara-Arab-Latn-233-2-1993 system test for الرِيَاض
2021-07-12T12:46:47.6772263Z      Failure/Error: expect(result).to eq(expected)
2021-07-12T12:46:47.6772617Z 
2021-07-12T12:46:47.6773073Z        expected: "al-Riyaḍ"
2021-07-12T12:46:47.6773638Z             got: "al-Riyāḍ"
2021-07-12T12:46:47.6773881Z 
2021-07-12T12:46:47.6774204Z        (compared using ==)
2021-07-12T12:46:47.6774918Z      # ./spec/interscript_spec.rb:32:in `block (8 levels) in <top (required)>'
2021-07-12T12:46:47.6775771Z      # ./spec/interscript_spec.rb:30:in `block (7 levels) in <top (required)>'
2021-07-12T12:46:47.6776175Z 
2021-07-12T12:46:47.6777175Z   5) Interscript Interscript::Compiler::Ruby iso-ara-Arab-Latn-233-2-1993 system test for سَأَلَ
2021-07-12T12:46:47.6778025Z      Failure/Error: expect(result).to eq(expected)
2021-07-12T12:46:47.6778382Z 
2021-07-12T12:46:47.6778821Z        expected: "Sa’al"
2021-07-12T12:46:47.6779306Z             got: "Sa’aal"
2021-07-12T12:46:47.6779539Z 
2021-07-12T12:46:47.6779861Z        (compared using ==)
2021-07-12T12:46:47.6780582Z      # ./spec/interscript_spec.rb:32:in `block (8 levels) in <top (required)>'
2021-07-12T12:46:47.6781440Z      # ./spec/interscript_spec.rb:30:in `block (7 levels) in <top (required)>'
2021-07-12T12:46:47.6781854Z 
2021-07-12T12:46:47.6782854Z   6) Interscript Interscript::Compiler::Ruby iso-ara-Arab-Latn-233-2-1993 system test for الشَّمْسُ
2021-07-12T12:46:47.6783967Z      Failure/Error: expect(result).to eq(expected)
2021-07-12T12:46:47.6784326Z 
2021-07-12T12:46:47.6784787Z        expected: "al-Šams"
2021-07-12T12:46:47.6785284Z             got: "al-Šaّms"
2021-07-12T12:46:47.6785523Z 
2021-07-12T12:46:47.6785859Z        (compared using ==)
2021-07-12T12:46:47.6786559Z      # ./spec/interscript_spec.rb:32:in `block (8 levels) in <top (required)>'
2021-07-12T12:46:47.6787417Z      # ./spec/interscript_spec.rb:30:in `block (7 levels) in <top (required)>'
2021-07-12T12:46:47.6787823Z 
2021-07-12T12:46:47.6788888Z   7) Interscript Interscript::Compiler::Javascript iso-ara-Arab-Latn-233-2-1993 system test for الرِيَاض
2021-07-12T12:46:47.6789763Z      Failure/Error: expect(result).to eq(expected)
2021-07-12T12:46:47.6790119Z 
2021-07-12T12:46:47.6790590Z        expected: "al-Riyaḍ"
2021-07-12T12:46:47.6791238Z             got: "al-Riyāḍ"
2021-07-12T12:46:47.6791481Z 
2021-07-12T12:46:47.6791822Z        (compared using ==)
2021-07-12T12:46:47.6792517Z      # ./spec/interscript_spec.rb:32:in `block (8 levels) in <top (required)>'
2021-07-12T12:46:47.6793379Z      # ./spec/interscript_spec.rb:30:in `block (7 levels) in <top (required)>'
2021-07-12T12:46:47.6793790Z 
2021-07-12T12:46:47.6794822Z   8) Interscript Interscript::Compiler::Javascript iso-ara-Arab-Latn-233-2-1993 system test for سَأَلَ
2021-07-12T12:46:47.6795704Z      Failure/Error: expect(result).to eq(expected)
2021-07-12T12:46:47.6796058Z 
2021-07-12T12:46:47.6796510Z        expected: "Sa’al"
2021-07-12T12:46:47.6796984Z             got: "Sa’aal"
2021-07-12T12:46:47.6797217Z 
2021-07-12T12:46:47.6797549Z        (compared using ==)
2021-07-12T12:46:47.6798329Z      # ./spec/interscript_spec.rb:32:in `block (8 levels) in <top (required)>'
2021-07-12T12:46:47.6799210Z      # ./spec/interscript_spec.rb:30:in `block (7 levels) in <top (required)>'
2021-07-12T12:46:47.6799625Z 
2021-07-12T12:46:47.6800684Z   9) Interscript Interscript::Compiler::Javascript iso-ara-Arab-Latn-233-2-1993 system test for الشَّمْسُ
2021-07-12T12:46:47.6801549Z      Failure/Error: expect(result).to eq(expected)
2021-07-12T12:46:47.6801909Z 
2021-07-12T12:46:47.6802367Z        expected: "al-Šams"
2021-07-12T12:46:47.6802855Z             got: "al-Šaّms"
2021-07-12T12:46:47.6803096Z 
2021-07-12T12:46:47.6803431Z        (compared using ==)
2021-07-12T12:46:47.6804128Z      # ./spec/interscript_spec.rb:32:in `block (8 levels) in <top (required)>'
2021-07-12T12:46:47.6804984Z      # ./spec/interscript_spec.rb:30:in `block (7 levels) in <top (required)>'
2021-07-12T12:46:47.7169579Z 
2021-07-12T12:46:47.7170588Z Finished in 36.61 seconds (files took 2.9 seconds to load)
2021-07-12T12:46:47.7171328Z 23334 examples, 9 failures
2021-07-12T12:46:47.7171722Z 
2021-07-12T12:46:47.7172161Z Failed examples:
2021-07-12T12:46:47.7172532Z 
2021-07-12T12:46:47.7174864Z rspec './spec/interscript_spec.rb[1:1:264:3]' # Interscript Interscript::Interpreter iso-ara-Arab-Latn-233-2-1993 system test for الرِيَاض
2021-07-12T12:46:47.7177148Z rspec './spec/interscript_spec.rb[1:1:264:7]' # Interscript Interscript::Interpreter iso-ara-Arab-Latn-233-2-1993 system test for سَأَلَ
2021-07-12T12:46:47.7179354Z rspec './spec/interscript_spec.rb[1:1:264:11]' # Interscript Interscript::Interpreter iso-ara-Arab-Latn-233-2-1993 system test for الشَّمْسُ
2021-07-12T12:46:47.7181549Z rspec './spec/interscript_spec.rb[1:2:264:3]' # Interscript Interscript::Compiler::Ruby iso-ara-Arab-Latn-233-2-1993 system test for الرِيَاض
2021-07-12T12:46:47.7183936Z rspec './spec/interscript_spec.rb[1:2:264:7]' # Interscript Interscript::Compiler::Ruby iso-ara-Arab-Latn-233-2-1993 system test for سَأَلَ
2021-07-12T12:46:47.7186161Z rspec './spec/interscript_spec.rb[1:2:264:11]' # Interscript Interscript::Compiler::Ruby iso-ara-Arab-Latn-233-2-1993 system test for الشَّمْسُ
2021-07-12T12:46:47.7188374Z rspec './spec/interscript_spec.rb[1:3:264:3]' # Interscript Interscript::Compiler::Javascript iso-ara-Arab-Latn-233-2-1993 system test for الرِيَاض
2021-07-12T12:46:47.7190610Z rspec './spec/interscript_spec.rb[1:3:264:7]' # Interscript Interscript::Compiler::Javascript iso-ara-Arab-Latn-233-2-1993 system test for سَأَلَ
2021-07-12T12:46:47.7193645Z rspec './spec/interscript_spec.rb[1:3:264:11]' # Interscript Interscript::Compiler::Javascript iso-ara-Arab-Latn-233-2-1993 system test for الشَّمْسُ
2021-07-12T12:46:47.7194520Z 
```

**Comment by webdev778** [comment]
We can use only one compiler, for instance Interscript::Interpreter for the maps repository.

**Comment by ronaldtse** [comment]
I didn't realize that there were three interpreters running! How it works is correct. Perhaps we can just update the RSpec description for an easier understanding.

**Comment by webdev778** [comment]
interscript/interscript#738
